name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
        pip install numpy
    - run: sudo apt update
    - run: sudo apt install inotify-tools
    - run: inotifywait -mr /home/runner/work/my-app/my-app/ --format '%T;%w;%f;%e' --timefmt %T -o /home/runner/inotify-logs.csv & echo 'optimizing-ci-builds'
    - run: touch starting_build_uses-checkout_11
    - run: rm starting_build_uses-checkout_11
    - uses: actions/checkout@v1
    - run: touch starting_build_SetupJDK18_12
    - run: rm starting_build_SetupJDK18_12
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - run: touch starting_build_BuildwithMaven_16
    - run: rm starting_build_BuildwithMaven_16
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - run: touch starting_finished_finished_8979874
      if: always()
    - run: rm starting_finished_finished_8979874
      if: always()
    - name: Execute py script # run file
      if: always()
      run: |
        python .github/workflows/script.py
    - name: Pushes analysis to another repository
      if: always()
      id: push_directory
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: 'optimizing-ci-builds-ci-analysis'
        destination-github-username: 'UT-SE-Research'
        destination-repository-name: 'ci-analyzes'
        target-branch: '1676917386-c0ae930'
        target-directory: 'my-app/.github/workflows/maven/build'
      continue-on-error: true
    - name: Check push directory exit code
      if: steps.push_directory.outcome == 'failure'
      run: |
        echo 'push failed, trying pull and then push'
        git config --global user.name 'UT-SE-Research'
        git add .
        git commit -m 'report ${{ github.head_ref }}'
        while ! git push origin {time}; do
          git pull --rebase https://github.com/UT-SE-Research/ci-analyzes.git 1676917386-c0ae930
          git push https://github.com/UT-SE-Research/ci-analyzes.git HEAD:1676917386-c0ae930
        done
